apiVersion: v2
name: parent-chart
description: A chart with local dependencies
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: database
    version: "1.0.0"
    # Local dependency (default location charts/database)
  - name: redis
    version: "2.0.0"
    repository: "file://./subcharts/redis"
  - name: nginx
    version: "1.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    # Remote dependency - should be ignored for local processing